name: Create ClassDiagramm

on:
  push:
    branches: master

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      
    - name: PlantUML CLI
      uses: lokkju/github-action-plantuml@v0.0.1
      
    - name: Commit files
      run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             mv ./uml/*.png ./diagram/
             git add ./diagram/*.png
             git status
             git commit -m "Add new diagram image" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: master
