name: Create ClassDiagramm

on:
  push:
    branches: master

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      
    - name: PlantUML CLI
      uses: lokkju/github-action-plantuml@v0.0.1
