name: Create ClassDiagramm

on:
  push:
    branches: master

jobs:
  build:
  
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check out current repository
      uses: actions/checkout@v2
      
    - name: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: uml
        message: "Render PlantUML files"
     
